### ISSUE TITLE
iOS issues

### ISSUE THREAD

**Issue by christhompson05** [jonoj-team/capacitor-fused-location#1]
Is this working on iOS? I ran into a couple issues. The first was that the podspec doesn't match the name generated in my podfile. After fixing this, FusedLocation always comes back as undefined.

**Comment by johannesnormannjensen** [comment]
Hi @christhompson05 

This repo only serves as a way to use the Google FusedLocation API on Android. I'll update this in the description.

**Comment by christhompson05** [comment]
@johannesnormannjensen Thanks, works like a charm on Android
