### ISSUE TITLE
[!] No podspec found for `JonojCapacitorFusedLocation` in `../../node_modules/@jonoj/capacitor-fused-location`

### ISSUE THREAD

**Issue by renege** [jonoj-team/capacitor-fused-location#2]
How to disable this error? @johannesnormannjensen

**Comment by renege** [comment]
Hello @johannesnormannjensen ?

**Comment by johannesnormannjensen** [comment]
Hi @renege 

I honestly don't know. I only use this for my Android project. If you have an idea on how to fix it you're more than welcome to contribute.

**Comment by bacques** [comment]
Hi @renege 

The podspec file is there, but with wrong name. I solved it by renaming node_modules/@jonoj/capacitor-fused-location/CapacitorFusedLocation.podspec into node_modules/@jonoj/capacitor-fused-location/JonojCapacitorFusedLocation.podspec.
You'll also have to edit the file and change the s.name attribute to 'JonojCapacitorFusedLocation'

**Comment by johannesnormannjensen** [comment]
@renege 
If you want to help me with a pull request I would appreciate that! :+1:

**Comment by johannesnormannjensen** [comment]
Closing. Fixed in #3
